Repository berTrindade/video-player-manager, pull requests merged in 2023-12, with the labels that each got.

#14 Add Project Summary and Architectural Decisions documents
  .nvmrc
  README.md
  docs/architectural-decision-records/architecture.md
  docs/architectural-decision-records/images/architecture_diagram.png
Labels: documentation

#16 Model DB and refactor Mongoose Schema
  app/_components/FluidPlayerConfigurator.tsx
  app/_components/forms/AdvertismentListForm.tsx
  app/_components/forms/ControlBarForm.tsx
  app/_components/forms/LayoutForm.tsx
  app/_components/forms/LogoForm.tsx
  app/_components/forms/MetadataForm.tsx
  app/_components/forms/MiniPlayerForm.tsx
  app/_components/forms/TimelinePreviewForm.tsx
  app/_components/player/AddEdit.tsx
  app/_helpers/client/transformFluidPlayerOptions.ts
  app/_helpers/server/db.ts
  app/_helpers/server/players-repo.ts
  app/_models/ConfiguratorOptions.ts
  app/_services/usePlayersService.ts
  app/api/players/[id]/route.ts
  app/api/players/route.ts
  docs/diagrams/database.png
Labels: backend

#31 Add static metadata object to root layout
  app/(app)/help/page.tsx
  app/(app)/layout.tsx
  app/(app)/page.tsx
  app/(app)/players/add/page.tsx
  app/(app)/players/edit/[id]/page.tsx
  app/(app)/players/page.tsx
  app/layout.tsx
Labels: frontend

#32 Add absolute imports and module path aliases
  app/(app)/layout.tsx
  app/(app)/players/add/page.tsx
  app/(app)/players/edit/[id]/page.tsx
  app/(app)/players/page.tsx
  app/api/players/[id]/route.ts
  app/api/players/route.ts
  components/FluidPlayerConfigurator.tsx
  components/FormMenu.tsx
  components/forms/AdvertismentForm.spec.tsx
  components/forms/AdvertismentForm.tsx
  components/forms/AdvertismentListForm.tsx
  components/forms/ControlBarForm.tsx
  components/forms/LayoutForm.tsx
  components/forms/LogoForm.tsx
  components/forms/MetadataForm.tsx
  components/forms/MiniPlayerForm.tsx
  components/forms/StaticPreviewForm.tsx
  components/forms/TimelinePreviewForm.tsx
  components/player/AddEdit.tsx
  components/sidebar/index.tsx
  components/sidebar/navigation/Profile.tsx
  components/sidebar/navigation/index.tsx
  constants/fluidPlayerConfigs.ts
  constants/formMenuItem.ts
  helpers/client/transformFluidPlayerOptions.ts
  helpers/server/api/error-handler.ts
  helpers/server/db.ts
  helpers/server/players-repo.ts
  services/usePlayersService.ts
  tsconfig.json
Labels: frontend

#33 Add missing options to Players form
  .gitignore
  app/(app)/layout.tsx
  app/(app)/players/add/page.tsx
  app/api/players/[id]/route.ts
  components/Alert.tsx
  components/FluidPlayerConfigurator.tsx
  components/FormMenu.tsx
  components/forms/AdvertisementForm.spec.tsx
  components/forms/AdvertisementForm.tsx
  components/forms/AdvertisementListForm.tsx
  components/forms/AdvertismentListForm.tsx
  components/forms/CallbacksForm.tsx
  components/forms/CaptionsForm.tsx
  components/forms/ContextMenuForm.tsx
  components/forms/ContextMenuLinkForm.tsx
  components/forms/ControlBarForm.tsx
  components/forms/HtmlOnPauseForm.tsx
  components/forms/LayoutForm.tsx
  components/forms/LogoForm.tsx
  components/forms/MetadataForm.tsx
  components/forms/MiniPlayerForm.tsx
  components/forms/PersistentSettingsForm.tsx
  components/forms/StaticPreviewForm.tsx
  components/forms/TheaterModeForm.tsx
  components/forms/TimelinePreviewForm.tsx
  components/forms/index.ts
  components/player/AddEdit.tsx
  components/sidebar/index.tsx
  components/sidebar/logo.tsx
  components/sidebar/navigation/Profile.tsx
  components/sidebar/navigation/navItem.tsx
  constants/formMenuItem.ts
  helpers/client/transformFluidPlayerOptions.ts
  helpers/server/players-repo.ts
  package-lock.json
  services/usePlayersService.ts
  yarn.lock
Labels: frontend

#34 Refactor file naming convention for cross-platform compatibility
  components/fields/checkbox-input.spec.tsx
  components/fields/checkbox-input.tsx
  components/fields/form-field.spec.tsx
  components/fields/form-field.tsx
  components/fields/function-input.tsx
  components/fields/index.ts
  components/fields/number-input.tsx
  components/fields/text-input.tsx
  components/fluid-player-configurator.tsx
  components/form-menu.tsx
  components/forms/advertisement-form.spec.tsx
  components/forms/advertisement-form.tsx
  components/forms/advertisement-list-form.tsx
  components/forms/callbacks-form.tsx
  components/forms/captions-form.tsx
  components/forms/context-menu-form.tsx
  components/forms/context-menu-link-form.tsx
  components/forms/control-bar-form.tsx
  components/forms/html-on-pause-form.tsx
  components/forms/index.ts
  components/forms/layout-form.tsx
  components/forms/logo-form.tsx
  components/forms/metadata-form.tsx
  components/forms/mini-player-form.tsx
  components/forms/persistent-settings-form.tsx
  components/forms/static-preview-form.tsx
  components/forms/theater-mode-form.tsx
  components/forms/timeline-preview-form.tsx
  components/player/add-edit.tsx
  components/player/index.ts
  components/sidebar/index.tsx
  components/sidebar/navigation/Profile.tsx
  components/sidebar/navigation/index.tsx
  components/sidebar/navigation/nav-item.tsx
  components/submit-button.tsx
  constants/fluid-player-configs.ts
  constants/form-menu-item.ts
  constants/index.ts
  docs/architectural-decision-records/images/architecture-diagram.png
  helpers/client/index.ts
  helpers/client/transform-fluid-player-options.ts
  helpers/client/use-fetch.ts
  models/configurator-options.ts
  models/fluid-player-configuration.ts
  models/index.ts
  services/index.ts
  services/use-alert-service.ts
  services/use-players-service.ts
Labels: frontend
