Repository berTrindade/video-player-manager, pull requests merged in 2024-01, with the labels that each got.

#49 Create Shareable Video landing page with a video based on a saved configuration (embedded)
  .env.local.example
  app/(app)/(dashboard)/help/page.tsx
  app/(app)/(dashboard)/layout.tsx
  app/(app)/(dashboard)/page.tsx
  app/(app)/(dashboard)/players/add/page.tsx
  app/(app)/(dashboard)/players/edit/[id]/page.tsx
  app/(app)/(dashboard)/players/page.tsx
  app/(app)/globals.css
  app/(app)/layout.tsx
  app/(embed)/embed/[id]/page.tsx
  app/(embed)/globals.css
  app/(embed)/layout.tsx
  app/(embed)/not-found.tsx
  app/api/players/[id]/route.ts
  app/layout.tsx
  components/fields/text-input.tsx
  components/forms/layout-form.tsx
  components/forms/theater-mode-form.tsx
  components/player/add-edit.tsx
  components/player/fluid-player-wrapper.css
  components/player/fluid-player-wrapper.tsx
  components/player/index.ts
  package-lock.json
  package.json
  services/use-players-service.ts
  yarn.lock
Labels: frontend

#63 Fix "ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead" error
  app/api/players/[id]/route.ts
  app/api/players/route.ts
Labels: bug

#61 feat(9): refactor players list page
  app/(app)/(dashboard)/players/page.tsx
  app/api/players/count/route.ts
  app/api/players/route.ts
  components/pagination.tsx
  components/players-list.tsx
  components/sidebar/constants.tsx
  constants/pagination.ts
  lib/client/use-fetch.ts
  lib/server/api/api-handler.ts
  lib/server/players-repo.ts
  services/use-players-service.ts
  types/player.ts
Labels: frontend, backend

#67 Renaming Environment Variables
  .env.local.example
  app/(app)/(dashboard)/players/page.tsx
  app/(embed)/embed/[id]/page.tsx
  lib/server/db.ts
Labels: enhancement

#68 Add back fork as dependency to package.json
  package.json
Labels: bug

#64 Add/Edit Player - Cleanup empty fields when saving form
  components/fields/function-input.tsx
  components/forms/advertisement-form.tsx
  components/forms/advertisement-list-form.tsx
  components/forms/callbacks-form.tsx
  components/forms/captions-form.tsx
  components/forms/context-menu-form.tsx
  components/forms/control-bar-form.tsx
  components/forms/html-on-pause-form.tsx
  components/forms/layout-form.tsx
  components/forms/logo-form.tsx
  components/forms/metadata-form.tsx
  components/forms/mini-player-form.tsx
  components/forms/persistent-settings-form.tsx
  components/forms/static-preview-form.tsx
  components/forms/theater-mode-form.tsx
  components/forms/timeline-preview-form.tsx
  components/player-preview.tsx
  components/player/fluid-player-wrapper.tsx
  constants/fluid-player-configs.ts
  lib/server/players-repo.ts
  lib/utils/errors/index.spec.ts
  lib/utils/errors/index.ts
  lib/utils/normalize-fluidplayer-configuration.ts
  lib/utils/type-validation.spec.ts
  lib/utils/type-validation.ts
  package-lock.json
  types/generic-types.ts
  types/index.ts
  yarn.lock
Labels: enhancement, frontend
